name = "caspian-digital-asset-xcas"
main = "index.js"
compatibility_date = "2026-09-07"

[vars]
# توکن ربات تلگرام خود را اینجا قرار دهید یا به عنوان Secret در کلودفلر تنظیم کنید
# TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"

[[d1_databases]]
binding = "DB"
database_name = "xcasbot"
database_id = "شناسه_دیتابیس_D1_شما"
